config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/new'

  root 'static_pages#home'
  get '/help',        to: 'static_pages#help'
  get '/about',       to: 'static_pages#about'
  get '/contact',     to: 'static_pages#contact'
  get '/datatest',    to: 'databases#datatest'
  get '/machinelist', to: 'databases#machinelist'
  get '/dataview',    to: 'databases#dataview'
  get '/emailsent',   to: 'databases#emailsent'
  get '/dailyreport', to: 'databases#dailyreport'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def datatest
  end

  def about
  end

  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1>About Page</h1>
<p>
  This is my sample app so far.  It's pretty basic.
  I like looking at this subreddit: <a href="https://www.reddit.com/r/minipainting" target="_blank">r/paintedminis</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>

<h1>Help Page</h1>
<p>
  This is my sample app so far.  It's pretty basic.
  I like looking at this subreddit: <a href="https://www.reddit.com/r/minipainting" target="_blank">r/paintedminis</a>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>USAC | Phoenix Web App</h1>

  <h2>
    This is the home page for the USAC | Phoenix Curing System web app.<br>
  </h2>
  
    USAC is the creator of a cutting-edge and completely automated curing process.<br>
    Visit us at <a href="https://www.usautocure.com/">usautocure.com</a> for more information.<br><br>

  <%= link_to "Log In", login_path, class: "btn btn-lg btn-primary" %><br><br>
  <%= image_tag  "Phoenix Logo.png", class: "img-responsive"%>
</div>