config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/new'

  root 'static_pages#home'
  get '/help',        to: 'static_pages#help'
  get '/about',       to: 'static_pages#about'
  get '/contact',     to: 'static_pages#contact'
  get '/datatest',    to: 'databases#datatest'
  get '/machinelist', to: 'databases#machinelist'
  get '/dataview',    to: 'databases#dataview'
  get '/emailsent',   to: 'databases#emailsent'
  get '/dailyreport', to: 'databases#dailyreport'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/controllers/databases_controller.rb
class DatabasesController < ApplicationController
  include HTTParty
  @@devid = "39a42baa-2057-4a2f-bdd3-7ac2ac8df44e"
  @@username = "admin"
  @@pass = "Msitec123"
  @@account = "US%20Autocure"

  def datatest
    ewonid = 786117
    response = HTTParty.get('https://data.talk2m.com/getstatus?t2maccount='+ @@account +'&t2musername='+ @@username +'&t2mpassword='+ @@pass +'&t2mdevid='+ @@devid +'&id='+ ewonid.to_s)
    @ewon_data = response.parsed_response
  end

  def show
    @mdatas = Mdatum.find(params[:id])
  end

  def machinelist
    response = HTTParty.get('https://data.talk2m.com/getewons?t2maccount='+ @@account +'&t2musername='+ @@username +'&t2mpassword='+ @@pass +'&t2mdevid='+ @@devid, :verify => false)
    @ewon_list = response.parsed_response

    e = Machine.new
    x = *(0..(@ewon_list["ewons"].length-1))
    x.each do |index|
      e.name = @ewon_list["ewons"][index]["name"]
      e.ewonid = @ewon_list["ewons"][index]["id"]
      e.lastsynchrodate = @ewon_list["ewons"][index]["lastSynchroDate"]
      e.save
    end
    @mlist = Machine.all
    @machineListJobs = Mdatum.where(timeStamp: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count
    @clockings = Mdatum.where(timeStamp: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).pluck(:clockIn, :clockOut)
    @machineListTotalTime = 0
    index = 0
    total = 0
    @clockings.each do
      clockin = Time.strptime(@clockings[index][0].to_s.slice(6..7)+":"+@clockings[index][0].to_s.slice(8..9), '%H:%M').to_i
      clockout = Time.strptime(@clockings[index][1].to_s.slice(6..7)+":"+@clockings[index][1].to_s.slice(8..9), '%H:%M').to_i
      clockedtime = clockout - clockin
      total = total + clockedtime
      index = index + 1
    end
    @machineListTotalTime = Time.at(total).utc.strftime("%H:%M")


  end

  def dataview
    @dataviewname = params[:name]
    ewonid = params[:ewonid]
    @ufromdate = params[:fromDate] 
    @utodate = params[:toDate]

    getewon(ewonid)

    if @ufromdate.nil? or @ufromdate.empty?
      @dataview_tags = Mdatum.where(timeStamp: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day, ewonid: ewonid).pluck(:customerName, :serial, 
        :timeStamp, :clockIn, :clockOut, :cureBaseTime, :cureClearTime,
        :customerID, :tempOverallAvg, :tempSensorAvg1, :tempSensorAvg2, 
        :tempSensorAvg3, :tempSensorAvg4, :tempSensorAvg5, :tempSensorAvg6, 
        :tempSensorAvg7, :tempSensorAvg8, :tempAmbientAvg, :humAmbientAvg)
      @ufromdate = Time.zone.now.strftime("%m/%d/%Y")
    else
      if @utodate.nil? or @utodate.empty?
        @utodate = Time.zone.now.strftime("%m/%d/%Y")
      end
      @dataview_tags = Mdatum.where(timeStamp: Date.strptime(@ufromdate, "%m/%d/%Y").beginning_of_day..Date.strptime(@utodate, "%m/%d/%Y").end_of_day, ewonid: ewonid).pluck(:customerName, :serial, 
        :timeStamp, :clockIn, :clockOut, :cureBaseTime, :cureClearTime,
        :customerID, :tempOverallAvg, :tempSensorAvg1, :tempSensorAvg2, 
        :tempSensorAvg3, :tempSensorAvg4, :tempSensorAvg5, :tempSensorAvg6, 
        :tempSensorAvg7, :tempSensorAvg8, :tempAmbientAvg, :humAmbientAvg)
    end
  end

  def dmpulldown
    m = Machine.all
    m.pluck(:ewonid).each do |id|
      puts id
      getewon(id.to_s)
    end
  end

  def tester 
    puts "bon"
  end

  def getewon(ewonid)
    response = HTTParty.get('https://data.talk2m.com/getewon?t2maccount='+ @@account +'&t2musername='+ @@username +'&t2mpassword='+ @@pass +'&t2mdevid='+ @@devid +'&id='+ewonid, :verify => false)
    @dataview_parsed = response.parsed_response

    e = Mdatum.new
    x = *(0..(@dataview_parsed ["tags"].length-1))
    x.each do |index|
      case @dataview_parsed["tags"][index]["name"]
      when "Customer_Name"
        e.customerName = @dataview_parsed["tags"][index]["value"]
      when "Serial_Number"
        e.serial = @dataview_parsed["tags"][index]["value"]
      when "Time_Stamp"
        timestring = @dataview_parsed["tags"][index]["value"].to_s
        #timestring = DateTime.strptime(timestring, %y%m%d%H%M)
        e.timeStamp = DateTime.strptime(timestring, '%y%m%d%H%M')
      when "Clock_In"
        e.clockIn = @dataview_parsed["tags"][index]["value"]
      when "Clock_Out"
        e.clockOut = @dataview_parsed["tags"][index]["value"]
      when "Cure_Base_Time"
        e.cureBaseTime = @dataview_parsed["tags"][index]["value"]
      when "Cure_Clear_Time"
        e.cureClearTime = @dataview_parsed["tags"][index]["value"]
      when "Customer_ID"
        e.customerID = @dataview_parsed["tags"][index]["value"]
      when "Temp_Overall_Avg"
        e.tempOverallAvg = @dataview_parsed["tags"][index]["value"]
      when "Temp_Sensor_Avg1"
        e.tempSensorAvg1 = @dataview_parsed["tags"][index]["value"]
      when "Temp_Sensor_Avg2"
        e.tempSensorAvg2 = @dataview_parsed["tags"][index]["value"]
      when "Temp_Sensor_Avg3"
        e.tempSensorAvg3 = @dataview_parsed["tags"][index]["value"]
      when "Temp_Sensor_Avg4"
        e.tempSensorAvg4 = @dataview_parsed["tags"][index]["value"]
      when "Temp_Sensor_Avg5"
        e.tempSensorAvg5 = @dataview_parsed["tags"][index]["value"]
      when "Temp_Sensor_Avg6"
        e.tempSensorAvg6 = @dataview_parsed["tags"][index]["value"]
      when "Temp_Sensor_Avg7"
        e.tempSensorAvg7 = @dataview_parsed["tags"][index]["value"]
      when "Temp_Sensor_Avg8"
        e.tempSensorAvg8 = @dataview_parsed["tags"][index]["value"]
      when "Temp_Ambient_Avg"
        e.tempAmbientAvg = @dataview_parsed["tags"][index]["value"]
      when "Hum_Ambient_Avg"
        e.humAmbientAvg = @dataview_parsed["tags"][index]["value"]
      end
    end
    e.ewonid = @dataview_parsed["id"]
    e.save
  end

  def emailsent()
    ApplicationMailer.mailer().deliver
  end

  def dailyreport()
    @dailytags = Mdatum.where(timeStamp: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).pluck( 
      :timeStamp, :clockIn, :clockOut, :cureBaseTime, :cureClearTime,
      :tempOverallAvg, :tempSensorAvg1, :tempSensorAvg2, 
      :tempSensorAvg3, :tempSensorAvg4, :tempSensorAvg5, :tempSensorAvg6, 
      :tempSensorAvg7, :tempSensorAvg8, :tempAmbientAvg, :humAmbientAvg)

    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename = 'dailyreport.xlsx'"
      }
      format.html {render :dailyreport }
    end
  end

end

app/helpers/databases_helper.rb
module DatabasesHelper
  def datepicker (form, field)
    form.text_field(field, data: {provide: "datepicker",
                                  'date-format': 'dd/mm/yyyy',
                                  'date-autoclose': 'true',
                                  'date-today-btn': 'linked',
                                  'date-today-highlight': 'true'}).html_safe
  end

  def totalTime ()
    total = 0
    @dataview_tags.each do |item|
      clockin = Time.strptime(item[3].to_s.slice(6..7)+":"+item[3].to_s.slice(8..9), '%H:%M').to_i
      clockout = Time.strptime(item[4].to_s.slice(6..7)+":"+item[4].to_s.slice(8..9), '%H:%M').to_i
      clockedtime = clockout - clockin
      total = total + clockedtime
    end
    return Time.at(total).utc.strftime("%H:%M")
  end

  def machinelistJobs ()
    return rand(100)
  end



end

app/views/databases/dailyreport.html.erb
<h1>Your report will download shortly</h1>

app/views/databases/datatest.html.erb
<% provide(:title, "Data Test")%>

<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>

<h1>Data Test Area</h1>
</br>

  </br>
<h2 class="text-left">Test zone for API requests</h2>
<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#dataStorm">Show Raw Data</button>
<div id="dataStorm" class="collapse">
  <%= @ewon_data %>
  </br></br>
  <%= @dtags %>
</div>

app/views/databases/dataview.html.erb
<head>
  <script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>
  <script>
  $( function() {
    $( "#fromDate" ).datepicker({
      endDate: "today",
      todayHighlight: true
    });
    $( "#toDate" ).datepicker({
      endDate: "today",
      todayHighlight: true
    });
  } );
  </script>
</head>

<% provide(:title, "Data View")%>
<input type="button" class="btn" value="Back to Machine List" onclick="window.location.href = '/machinelist';" /> 
<h1>Machine:&nbsp<%= @dataviewname %></h1>

<div id="card_holder" class="" style="width: 100%; height: 20rem;">

  <div class="panel panel-primary" style="width: 18rem; float: left; box-shadow: 0 3px 6px rgba(0,0,0,.25);">
    <div class="panel-heading">
      <h3 class="panel-title center-block" id="job_count" style="height: 12rem; font-size: 12rem; text-align: center;">#</h3>
    </div>
    <div class="panel-body" style="text-align: center; font-size: 1.25em;">
      <b>Jobs Ran</b>
    </div>
  </div>

  <div style="width: 20px; height: 20rem; float: left;"></div>

  <div class="panel panel-primary" style="width: 18rem; float: left; box-shadow: 0 3px 6px rgba(0,0,0,.25);">
    <div class="panel-heading">
      <h3 class="panel-title center-block align-middle" id="job_count" style="line-height: 2.1em; height: 12rem; font-size: 4em; text-align: center;"><%= totalTime() %></h3>
    </div>
    <div class="panel-body" style="text-align: center; font-size: 1.25em;">
      <b>Total Time</b>
    </div>
  </div>

</div>
<br><br>
<div class="center"> 
  <%= form_tag("/dataview", method: "get") do %>
    <%= label_tag(:date, "From: ") %>
    <%= text_field_tag(:fromDate, @ufromdate, autocomplete: :off) %>
      <%= label_tag(:date, "To: ") %>
    <%= text_field_tag(:toDate, @utodate, autocomplete: :off) %>
    <%= hidden_field_tag(:ewonid, params[:ewonid])%>
    <%= hidden_field_tag(:name, params[:name])%>
    <%= submit_tag("Select", :class=>"btn") %>
  <% end %>

</div>
</br>

</br>
<div class="inline">
  <input type="button" class="btn btn-primary" value="Update" onClick="document.location.reload(true)">
  <button class="btn btn-success pull-right" onclick="exportTableToCSV('report.csv')">Export Report</button>
</div>


<table class="table table-striped" id="myTable">
  <thead class="thead-dark">
    <tr>
      <th>Time Stamp</th>
      <th>Clock In</th>
      <th>Clock Out</th>
      <th>Cure Base Time</th>
      <th>Cure Clear Time</th>
      <!--<th>Customer ID</th>-->
      <th>Temp Avg</th>
      <th>Temp Avg 1</th>
      <th>Temp Avg 2</th>
      <th>Temp Avg 3</th>
      <th>Temp Avg 4</th>
      <th>Temp Avg 5</th>
      <th>Temp Avg 6</th>
      <th>Temp Avg 7</th>
      <th>Temp Avg 8</th>
      <th>Temp Ambient</th>
      <th>Hum Ambient</th>
    </tr>
  </thead>
  <tbody>
      <% @dataview_tags.each do |item| %>
        <tr>
          <td><%= item[2] %></td>
          <td><%= item[3].to_s.slice(6..7)+":"+item[3].to_s.slice(8..9) %></td>
          <td><%= item[4].to_s.slice(6..7)+":"+item[4].to_s.slice(8..9) %></td>
          <td><%= item[5] %></td>
          <td><%= item[6] %></td>
          <!--<td><%= item[7] %></td>-->
          <td><%= item[8] %></td>
          <td><%= item[9] %></td>
          <td><%= item[10] %></td>
          <td><%= item[11] %></td>
          <td><%= item[12] %></td>
          <td><%= item[13] %></td>
          <td><%= item[14] %></td>
          <td><%= item[15] %></td>
          <td><%= item[16] %></td>
          <td><%= item[17] %></td>
          <td><%= item[18] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>



    	<script>
function downloadCSV(csv, filename) {
    var csvFile;
    var downloadLink;

    // CSV file
    csvFile = new Blob([csv], {type: "text/csv"});

    // Download link
    downloadLink = document.createElement("a");

    // File name
    downloadLink.download = filename;

    // Create a link to the file
    downloadLink.href = window.URL.createObjectURL(csvFile);

    // Hide download link
    downloadLink.style.display = "none";

    // Add the link to DOM
    document.body.appendChild(downloadLink);

    // Click download link
    downloadLink.click();
}

function exportTableToCSV(filename) {
    var csv = [];
	var rows = document.querySelectorAll("table tr");
	
    for (var i = 0; i < rows.length; i++) {
		var row = [], cols = rows[i].querySelectorAll("td, th");
		
        for (var j = 0; j < cols.length; j++) 
            row.push(cols[j].innerText);
        
		csv.push(row.join(","));		
	}

    // Download CSV file
    downloadCSV(csv.join("\n"), filename);
}

    $(document).ready(function() {
        var x = document.getElementById("myTable").rows.length;
        var job_count = document.getElementById("job_count");
        job_count.innerHTML = x-1;
    });
</script>




app/views/databases/emailsent.html.erb
<h1>Email sent!</h1>

app/views/databases/machinelist.html.erb
<% provide(:title, "Machine List")%>

<h1>Machine List</h1>
<h2>Click on a machine listed below to view</h2>
<div id="card_holder" class="" style="width: 100%; height: 20rem;">

  <div class="panel panel-primary" style="width: 18rem; float: left; box-shadow: 0 3px 6px rgba(0,0,0,.25);">
    <div class="panel-heading">
      <h3 class="panel-title center-block" style="height: 12rem; font-size: 12rem; text-align: center;"><%= @machineListJobs %></h3>
    </div>
    <div class="panel-body" style="text-align: center; font-size: 1.25em;">
      <b>Jobs Ran Today</b>
    </div>
  </div>
    
  <div style="width: 20px; height: 20rem; float: left;"></div>

  <div class="panel panel-primary" style="width: 18rem; float: left; box-shadow: 0 3px 6px rgba(0,0,0,.25);">
    <div class="panel-heading">
      <h3 class="panel-title center-block align-middle" style="line-height: 2.1em; height: 12rem; font-size: 4em; text-align: center;"><%= @machineListTotalTime %></h3>
    </div>
    <div class="panel-body" style="text-align: center; font-size: 1.25em;">
      <b>Total Time Today</b>
    </div>
  </div>

</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>ID</th>
    </tr>
  </thead>
  <tbody>
    <% @mlist.each do |item| %>
      <tr>
        <td><%= link_to item.name, dataview_path(:ewonid => item.ewonid, :name => item.name) %></td>
        <td><%= item.ewonid %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</br>
<!--
<div class="btn btn-primary">
  <%= link_to 'Email Test', emailsent_path %>
</div>

  <%=
  link_to 'Download as Excel',
  dailyreport_path(format: :xlsx)
  %>
-->



